// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID          pgtype.UUID
	Fullname    pgtype.Text
	Email       string
	AvatarUrl   pgtype.Text
	Bio         pgtype.Text
	Slug        pgtype.Text
	DateOfBirth pgtype.Timestamptz
	Gender      pgtype.Bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Sentence    pgtype.Text
	Author      pgtype.Text
}
