// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID          pgtype.UUID
	Fullname    string
	Email       string
	AvatarUrl   pgtype.Text
	Bio         pgtype.Text
	Slug        pgtype.Text
	DateOfBirth pgtype.Date
	Gender      string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	Sentence    string
	Author      pgtype.Text
}
