// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type UserProfile struct {
	UserID      pgtype.UUID
	Fullname    string
	Username    string
	AvatarUrl   pgtype.Text
	Bio         pgtype.Text
	Slug        pgtype.Text
	DateOfBirth pgtype.Date
	Gender      bool
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}
