// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID     int64
	Name   string
	Bio    pgtype.Text
	UserID pgtype.Int8
}

type User struct {
	ID      int64
	Name    string
	Age     pgtype.Int4
	Gender  pgtype.Text
	Address pgtype.Text
}
