// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserProfile = `-- name: GetUserProfile :one
select id, fullname, email, avatar_url, bio, slug, date_of_birth, gender, created_at, updated_at, sentence, author from users where id = $1
`

func (q *Queries) GetUserProfile(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserProfile, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Email,
		&i.AvatarUrl,
		&i.Bio,
		&i.Slug,
		&i.DateOfBirth,
		&i.Gender,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Sentence,
		&i.Author,
	)
	return i, err
}
