// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"user_service/internal/controller"
	"user_service/internal/repos"
	"user_service/internal/services"
)

// Injectors from user.wire.go:

func InjectUserController() *controller.UserController {
	iUserRepo := repos.NewUserRepo()
	iUserService := services.NewUserService(iUserRepo)
	userController := controller.NewUserController(iUserService)
	return userController
}
