// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: common/outbox.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OutboxStatus int32

const (
	OutboxStatus_OUTBOX_STATUS_UNSPECIFIED OutboxStatus = 0 // Default value, should not be used
	OutboxStatus_OUTBOX_STATUS_PENDING     OutboxStatus = 1 // Event is pending processing
	OutboxStatus_OUTBOX_STATUS_PROCESSED   OutboxStatus = 2 // Event has been processed successfully
	OutboxStatus_OUTBOX_STATUS_FAILED      OutboxStatus = 3 // Event processing failed
)

// Enum value maps for OutboxStatus.
var (
	OutboxStatus_name = map[int32]string{
		0: "OUTBOX_STATUS_UNSPECIFIED",
		1: "OUTBOX_STATUS_PENDING",
		2: "OUTBOX_STATUS_PROCESSED",
		3: "OUTBOX_STATUS_FAILED",
	}
	OutboxStatus_value = map[string]int32{
		"OUTBOX_STATUS_UNSPECIFIED": 0,
		"OUTBOX_STATUS_PENDING":     1,
		"OUTBOX_STATUS_PROCESSED":   2,
		"OUTBOX_STATUS_FAILED":      3,
	}
)

func (x OutboxStatus) Enum() *OutboxStatus {
	p := new(OutboxStatus)
	*p = x
	return p
}

func (x OutboxStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutboxStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_outbox_proto_enumTypes[0].Descriptor()
}

func (OutboxStatus) Type() protoreflect.EnumType {
	return &file_common_outbox_proto_enumTypes[0]
}

func (x OutboxStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutboxStatus.Descriptor instead.
func (OutboxStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_outbox_proto_rawDescGZIP(), []int{0}
}

type Outbox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	AggregateType string                 `protobuf:"bytes,2,opt,name=aggregate_type,json=aggregateType,proto3" json:"aggregate_type"`
	AggregateId   string                 `protobuf:"bytes,3,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id"`
	EventType     string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status"`
	OccurredAt    int64                  `protobuf:"varint,7,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at"`
	ProcessedAt   *int64                 `protobuf:"varint,8,opt,name=processed_at,json=processedAt,proto3,oneof" json:"processed_at"`
	ErrorMessage  *string                `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message"`
	RetryCount    int32                  `protobuf:"varint,10,opt,name=retry_count,json=retryCount,proto3" json:"retry_count"`
	RequestId     string                 `protobuf:"bytes,11,opt,name=request_id,json=requestId,proto3" json:"request_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Outbox) Reset() {
	*x = Outbox{}
	mi := &file_common_outbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outbox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outbox) ProtoMessage() {}

func (x *Outbox) ProtoReflect() protoreflect.Message {
	mi := &file_common_outbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outbox.ProtoReflect.Descriptor instead.
func (*Outbox) Descriptor() ([]byte, []int) {
	return file_common_outbox_proto_rawDescGZIP(), []int{0}
}

func (x *Outbox) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Outbox) GetAggregateType() string {
	if x != nil {
		return x.AggregateType
	}
	return ""
}

func (x *Outbox) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *Outbox) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Outbox) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Outbox) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Outbox) GetOccurredAt() int64 {
	if x != nil {
		return x.OccurredAt
	}
	return 0
}

func (x *Outbox) GetProcessedAt() int64 {
	if x != nil && x.ProcessedAt != nil {
		return *x.ProcessedAt
	}
	return 0
}

func (x *Outbox) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *Outbox) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *Outbox) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_common_outbox_proto protoreflect.FileDescriptor

const file_common_outbox_proto_rawDesc = "" +
	"\n" +
	"\x13common/outbox.proto\x12\x06common\"\x89\x03\n" +
	"\x06Outbox\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eaggregate_type\x18\x02 \x01(\tR\raggregateType\x12!\n" +
	"\faggregate_id\x18\x03 \x01(\tR\vaggregateId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1f\n" +
	"\voccurred_at\x18\a \x01(\x03R\n" +
	"occurredAt\x12&\n" +
	"\fprocessed_at\x18\b \x01(\x03H\x00R\vprocessedAt\x88\x01\x01\x12(\n" +
	"\rerror_message\x18\t \x01(\tH\x01R\ferrorMessage\x88\x01\x01\x12\x1f\n" +
	"\vretry_count\x18\n" +
	" \x01(\x05R\n" +
	"retryCount\x12\x1d\n" +
	"\n" +
	"request_id\x18\v \x01(\tR\trequestIdB\x0f\n" +
	"\r_processed_atB\x10\n" +
	"\x0e_error_message*\x7f\n" +
	"\fOutboxStatus\x12\x1d\n" +
	"\x19OUTBOX_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15OUTBOX_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17OUTBOX_STATUS_PROCESSED\x10\x02\x12\x18\n" +
	"\x14OUTBOX_STATUS_FAILED\x10\x03B\x0eZ\fproto/commonb\x06proto3"

var (
	file_common_outbox_proto_rawDescOnce sync.Once
	file_common_outbox_proto_rawDescData []byte
)

func file_common_outbox_proto_rawDescGZIP() []byte {
	file_common_outbox_proto_rawDescOnce.Do(func() {
		file_common_outbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_outbox_proto_rawDesc), len(file_common_outbox_proto_rawDesc)))
	})
	return file_common_outbox_proto_rawDescData
}

var file_common_outbox_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_outbox_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_outbox_proto_goTypes = []any{
	(OutboxStatus)(0), // 0: common.OutboxStatus
	(*Outbox)(nil),    // 1: common.Outbox
}
var file_common_outbox_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_outbox_proto_init() }
func file_common_outbox_proto_init() {
	if File_common_outbox_proto != nil {
		return
	}
	file_common_outbox_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_outbox_proto_rawDesc), len(file_common_outbox_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_outbox_proto_goTypes,
		DependencyIndexes: file_common_outbox_proto_depIdxs,
		EnumInfos:         file_common_outbox_proto_enumTypes,
		MessageInfos:      file_common_outbox_proto_msgTypes,
	}.Build()
	File_common_outbox_proto = out.File
	file_common_outbox_proto_goTypes = nil
	file_common_outbox_proto_depIdxs = nil
}
