// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: common/syncdatabase.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncDatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatabaseName  *string                `protobuf:"bytes,1,opt,name=database_name,json=databaseName,proto3,oneof" json:"database_name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncDatabaseRequest) Reset() {
	*x = SyncDatabaseRequest{}
	mi := &file_common_syncdatabase_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncDatabaseRequest) ProtoMessage() {}

func (x *SyncDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_syncdatabase_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncDatabaseRequest.ProtoReflect.Descriptor instead.
func (*SyncDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_common_syncdatabase_proto_rawDescGZIP(), []int{0}
}

func (x *SyncDatabaseRequest) GetDatabaseName() string {
	if x != nil && x.DatabaseName != nil {
		return *x.DatabaseName
	}
	return ""
}

var File_common_syncdatabase_proto protoreflect.FileDescriptor

const file_common_syncdatabase_proto_rawDesc = "" +
	"\n" +
	"\x19common/syncdatabase.proto\x12\x06common\x1a\x13common/common.proto\"Q\n" +
	"\x13SyncDatabaseRequest\x12(\n" +
	"\rdatabase_name\x18\x01 \x01(\tH\x00R\fdatabaseName\x88\x01\x01B\x10\n" +
	"\x0e_database_name2Y\n" +
	"\x13SyncDatabaseService\x12B\n" +
	"\fSyncDatabase\x12\x1b.common.SyncDatabaseRequest\x1a\x15.common.EmptyResponseB\x0eZ\fproto/commonb\x06proto3"

var (
	file_common_syncdatabase_proto_rawDescOnce sync.Once
	file_common_syncdatabase_proto_rawDescData []byte
)

func file_common_syncdatabase_proto_rawDescGZIP() []byte {
	file_common_syncdatabase_proto_rawDescOnce.Do(func() {
		file_common_syncdatabase_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_syncdatabase_proto_rawDesc), len(file_common_syncdatabase_proto_rawDesc)))
	})
	return file_common_syncdatabase_proto_rawDescData
}

var file_common_syncdatabase_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_syncdatabase_proto_goTypes = []any{
	(*SyncDatabaseRequest)(nil), // 0: common.SyncDatabaseRequest
	(*EmptyResponse)(nil),       // 1: common.EmptyResponse
}
var file_common_syncdatabase_proto_depIdxs = []int32{
	0, // 0: common.SyncDatabaseService.SyncDatabase:input_type -> common.SyncDatabaseRequest
	1, // 1: common.SyncDatabaseService.SyncDatabase:output_type -> common.EmptyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_syncdatabase_proto_init() }
func file_common_syncdatabase_proto_init() {
	if File_common_syncdatabase_proto != nil {
		return
	}
	file_common_common_proto_init()
	file_common_syncdatabase_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_syncdatabase_proto_rawDesc), len(file_common_syncdatabase_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_syncdatabase_proto_goTypes,
		DependencyIndexes: file_common_syncdatabase_proto_depIdxs,
		MessageInfos:      file_common_syncdatabase_proto_msgTypes,
	}.Build()
	File_common_syncdatabase_proto = out.File
	file_common_syncdatabase_proto_goTypes = nil
	file_common_syncdatabase_proto_depIdxs = nil
}
