// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: common/syncdatabase.proto

package common

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SyncDatabaseService_SyncDatabase_FullMethodName = "/common.SyncDatabaseService/SyncDatabase"
)

// SyncDatabaseServiceClient is the client API for SyncDatabaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SyncDatabaseServiceClient interface {
	SyncDatabase(ctx context.Context, in *SyncDatabaseRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type syncDatabaseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncDatabaseServiceClient(cc grpc.ClientConnInterface) SyncDatabaseServiceClient {
	return &syncDatabaseServiceClient{cc}
}

func (c *syncDatabaseServiceClient) SyncDatabase(ctx context.Context, in *SyncDatabaseRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, SyncDatabaseService_SyncDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncDatabaseServiceServer is the server API for SyncDatabaseService service.
// All implementations must embed UnimplementedSyncDatabaseServiceServer
// for forward compatibility.
type SyncDatabaseServiceServer interface {
	SyncDatabase(context.Context, *SyncDatabaseRequest) (*EmptyResponse, error)
	mustEmbedUnimplementedSyncDatabaseServiceServer()
}

// UnimplementedSyncDatabaseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSyncDatabaseServiceServer struct{}

func (UnimplementedSyncDatabaseServiceServer) SyncDatabase(context.Context, *SyncDatabaseRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncDatabase not implemented")
}
func (UnimplementedSyncDatabaseServiceServer) mustEmbedUnimplementedSyncDatabaseServiceServer() {}
func (UnimplementedSyncDatabaseServiceServer) testEmbeddedByValue()                             {}

// UnsafeSyncDatabaseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncDatabaseServiceServer will
// result in compilation errors.
type UnsafeSyncDatabaseServiceServer interface {
	mustEmbedUnimplementedSyncDatabaseServiceServer()
}

func RegisterSyncDatabaseServiceServer(s grpc.ServiceRegistrar, srv SyncDatabaseServiceServer) {
	// If the following call pancis, it indicates UnimplementedSyncDatabaseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SyncDatabaseService_ServiceDesc, srv)
}

func _SyncDatabaseService_SyncDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncDatabaseServiceServer).SyncDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncDatabaseService_SyncDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncDatabaseServiceServer).SyncDatabase(ctx, req.(*SyncDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SyncDatabaseService_ServiceDesc is the grpc.ServiceDesc for SyncDatabaseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyncDatabaseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "common.SyncDatabaseService",
	HandlerType: (*SyncDatabaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncDatabase",
			Handler:    _SyncDatabaseService_SyncDatabase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common/syncdatabase.proto",
}
