// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: authentication_service/authentication.v1.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JwtToken      string                 `protobuf:"bytes,1,opt,name=jwtToken,proto3" json:"jwtToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_authentication_service_authentication_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_service_authentication_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_authentication_service_authentication_v1_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateTokenRequest) GetJwtToken() string {
	if x != nil {
		return x.JwtToken
	}
	return ""
}

// The response message
type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_authentication_service_authentication_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_service_authentication_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_authentication_service_authentication_v1_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateTokenResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_authentication_service_authentication_v1_proto protoreflect.FileDescriptor

const file_authentication_service_authentication_v1_proto_rawDesc = "" +
	"\n" +
	".authentication_service/authentication.v1.proto\x12\x04grpc\"2\n" +
	"\x14ValidateTokenRequest\x12\x1a\n" +
	"\bjwtToken\x18\x01 \x01(\tR\bjwtToken\"/\n" +
	"\x15ValidateTokenResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result2a\n" +
	"\x15AuthenticationService\x12H\n" +
	"\rValidateToken\x12\x1a.grpc.ValidateTokenRequest\x1a\x1b.grpc.ValidateTokenResponseB-Z+internal/grpc/gen_code/authentication.v1;v1b\x06proto3"

var (
	file_authentication_service_authentication_v1_proto_rawDescOnce sync.Once
	file_authentication_service_authentication_v1_proto_rawDescData []byte
)

func file_authentication_service_authentication_v1_proto_rawDescGZIP() []byte {
	file_authentication_service_authentication_v1_proto_rawDescOnce.Do(func() {
		file_authentication_service_authentication_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authentication_service_authentication_v1_proto_rawDesc), len(file_authentication_service_authentication_v1_proto_rawDesc)))
	})
	return file_authentication_service_authentication_v1_proto_rawDescData
}

var file_authentication_service_authentication_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_authentication_service_authentication_v1_proto_goTypes = []any{
	(*ValidateTokenRequest)(nil),  // 0: grpc.ValidateTokenRequest
	(*ValidateTokenResponse)(nil), // 1: grpc.ValidateTokenResponse
}
var file_authentication_service_authentication_v1_proto_depIdxs = []int32{
	0, // 0: grpc.AuthenticationService.ValidateToken:input_type -> grpc.ValidateTokenRequest
	1, // 1: grpc.AuthenticationService.ValidateToken:output_type -> grpc.ValidateTokenResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_authentication_service_authentication_v1_proto_init() }
func file_authentication_service_authentication_v1_proto_init() {
	if File_authentication_service_authentication_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authentication_service_authentication_v1_proto_rawDesc), len(file_authentication_service_authentication_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authentication_service_authentication_v1_proto_goTypes,
		DependencyIndexes: file_authentication_service_authentication_v1_proto_depIdxs,
		MessageInfos:      file_authentication_service_authentication_v1_proto_msgTypes,
	}.Build()
	File_authentication_service_authentication_v1_proto = out.File
	file_authentication_service_authentication_v1_proto_goTypes = nil
	file_authentication_service_authentication_v1_proto_depIdxs = nil
}
