// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"user_service/internal/grpc/controller"
	"user_service/internal/grpc/mapper"
	"user_service/internal/grpc/repos"
	"user_service/internal/grpc/services"
)

// Injectors from user.wire.go:

func InjectUserController() *controller.UserController {
	userRepo := repos.NewUserRepo()
	userMapper := mapper.NewUserMapper()
	userService := services.NewUserService(userRepo, userMapper)
	userController := controller.NewUserController(userService)
	return userController
}
