// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: user_service/common.user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserProfileItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Fullname      string                 `protobuf:"bytes,2,opt,name=fullname,proto3" json:"fullname"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email"`
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url"`
	Bio           string                 `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio"`
	Slug          string                 `protobuf:"bytes,6,opt,name=slug,proto3" json:"slug"`
	DateOfBirth   int64                  `protobuf:"varint,7,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth"`
	Gender        bool                   `protobuf:"varint,8,opt,name=gender,proto3" json:"gender"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt     int64                  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	Sentence      string                 `protobuf:"bytes,11,opt,name=sentence,proto3" json:"sentence"`
	Author        string                 `protobuf:"bytes,12,opt,name=author,proto3" json:"author"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfileItem) Reset() {
	*x = UserProfileItem{}
	mi := &file_user_service_common_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfileItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileItem) ProtoMessage() {}

func (x *UserProfileItem) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_common_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfileItem.ProtoReflect.Descriptor instead.
func (*UserProfileItem) Descriptor() ([]byte, []int) {
	return file_user_service_common_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserProfileItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserProfileItem) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *UserProfileItem) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserProfileItem) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UserProfileItem) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UserProfileItem) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *UserProfileItem) GetDateOfBirth() int64 {
	if x != nil {
		return x.DateOfBirth
	}
	return 0
}

func (x *UserProfileItem) GetGender() bool {
	if x != nil {
		return x.Gender
	}
	return false
}

func (x *UserProfileItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *UserProfileItem) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *UserProfileItem) GetSentence() string {
	if x != nil {
		return x.Sentence
	}
	return ""
}

func (x *UserProfileItem) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

var File_user_service_common_user_proto protoreflect.FileDescriptor

const file_user_service_common_user_proto_rawDesc = "" +
	"\n" +
	"\x1euser_service/common.user.proto\x12\x04user\"\xc6\x02\n" +
	"\x0fUserProfileItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bfullname\x18\x02 \x01(\tR\bfullname\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12\x10\n" +
	"\x03bio\x18\x05 \x01(\tR\x03bio\x12\x12\n" +
	"\x04slug\x18\x06 \x01(\tR\x04slug\x12\"\n" +
	"\rdate_of_birth\x18\a \x01(\x03R\vdateOfBirth\x12\x16\n" +
	"\x06gender\x18\b \x01(\bR\x06gender\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\x12\x1a\n" +
	"\bsentence\x18\v \x01(\tR\bsentence\x12\x16\n" +
	"\x06author\x18\f \x01(\tR\x06authorB\fZ\n" +
	"proto/userb\x06proto3"

var (
	file_user_service_common_user_proto_rawDescOnce sync.Once
	file_user_service_common_user_proto_rawDescData []byte
)

func file_user_service_common_user_proto_rawDescGZIP() []byte {
	file_user_service_common_user_proto_rawDescOnce.Do(func() {
		file_user_service_common_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_service_common_user_proto_rawDesc), len(file_user_service_common_user_proto_rawDesc)))
	})
	return file_user_service_common_user_proto_rawDescData
}

var file_user_service_common_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_user_service_common_user_proto_goTypes = []any{
	(*UserProfileItem)(nil), // 0: user.UserProfileItem
}
var file_user_service_common_user_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_service_common_user_proto_init() }
func file_user_service_common_user_proto_init() {
	if File_user_service_common_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_service_common_user_proto_rawDesc), len(file_user_service_common_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_service_common_user_proto_goTypes,
		DependencyIndexes: file_user_service_common_user_proto_depIdxs,
		MessageInfos:      file_user_service_common_user_proto_msgTypes,
	}.Build()
	File_user_service_common_user_proto = out.File
	file_user_service_common_user_proto_goTypes = nil
	file_user_service_common_user_proto_depIdxs = nil
}
